# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='status',
            field=models.NullBooleanField(default=False),
        ),
    ]
