# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-12-27 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtel', '0004_auto_20191223_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='HbbActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=13, null=True)),
                ('alter_msisdn', models.CharField(max_length=13, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AppRegistration',
        ),
    ]
