# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-12-28 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtel', '0008_auto_20191228_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='msisdn',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
