# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-21 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airtel', '0010_auto_20191228_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=13, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='download',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='airtel.Product'),
            preserve_default=False,
        ),
    ]
