# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-24 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airtel', '0012_auto_20200124_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='android_url',
            new_name='android',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='ios_url',
            new_name='ios',
        ),
    ]
