# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-12-28 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airtel', '0007_agents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agents',
            new_name='Agent',
        ),
    ]
