# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-24 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airtel', '0011_auto_20200121_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('android_url', models.CharField(blank=True, max_length=250, null=True)),
                ('ios_url', models.CharField(blank=True, max_length=250, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_url', to='airtel.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='download',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='airtel.Product'),
        ),
    ]
